// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qnogrefdktpihjagsexl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFub2dyZWZka3RwaWhqYWdzZXhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3NTc1MzIsImV4cCI6MjA3MTMzMzUzMn0.Pso0hm9qZFotFVrwzX3O24F1y_8GWyfoR0ThhIxyWMw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});